name: google_maps_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies: #TODO LO QUE ESTA ABAJO DE ESTA LINEA DEBE ESTAR IDENTADA COMO SE INDICA
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.0.3 #al mismo nivel que la palabra flutter, para poder usar la libreria en el main luego
  geolocator: ^2.1.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

