name: flutter_ui_avanzadas
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.4 #dependencia para poder usar imagenes svg

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/pages/login/clouds.svg
     - assets/pages/login/man.svg
     - assets/pages/login/woman.svg
     - assets/pages/login/icons/mail.svg
     - assets/pages/login/icons/smart-key.svg
     - assets/pages/login/icons/facebook.svg
     - assets/pages/login/icons/google.svg



  #ESPACIO PARA AGREGAR FUENTES, EN ESTE CASO SACAMOS LAS QUE HAY Y COLOCAMOS LAS QUE SE REQUIEREN
  #EN ESTE CASO LAS FUENTES SE DESCARGAN DE GOOGLE FONST Y SE GUARDAN SOLO LOS ARCHIVOS REQUERIDOS EN UNA CARPETA
  fonts:
    - family: sans #nombre de la familia de fuentes
      fonts:
       - asset: assets/fonts/OpenSans-Bold.ttf #LAS FUENTES SE GUARDARON EN LA CARPETA INDICADA, Solo los archivos deseados, no todos
         weight: 700
       - asset: assets/fonts/OpenSans-Light.ttf
         weight: 300
       - asset: assets/fonts/OpenSans-Regular.ttf
         weight: 400
       - asset: assets/fonts/OpenSans-SemiBold.ttf
         weight: 600
    - family: raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
